import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Provider from "./provider";
import {Open_Sans, Poppins} from 'next/font/google';

const open = Open_Sans({ subsets: ["latin"], weight: ["300", "400", "500", "600", "700", "800"], variable: "--font-open" });
const pop = Poppins({ subsets: ["latin"], weight: ["100",  "200",  "300",  "400",  "500",  "600",  "700",  "800",  "900"], variable: "--font-pop" });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${open.variable} ${pop.variable} antialiased`}
        >
          <Provider>
            {children}
          </Provider>
        </body>
      </html>
    </ClerkProvider>
  );
}
